### ISSUE TITLE
No tarsnaprc file installed on the host?

### ISSUE THREAD

**Issue by maknz** [pmbauer/ansible-tarsnap#8]
Hi there,

I've got a playbook using the tarsnap role:

```yml
---
- hosts: thehost
  become: yes
  roles:
  - role: tarsnap
    tarsnap_version: 1.0.37
    tarsnap_keyfile: "/root/tarsnap.key"
    tarsnap_cache: "/usr/local/tarsnap-cache"
```

However, I can't seem to find the `.tarsnaprc` file that is supposed to be installed, with the cache and such excluded (from the README). There is a config file at `/usr/local/etc/tarsnap.conf.sample` after installation, but it seems to just be boilerplate and doesn't reflect the options used in the playbook.
